### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Iant20** [orvice/v2ray-mu#4]
What is the reason for these errors? I'm not familiar with Go language.
```goroutine 18 [running]:
github.com/orvice/v2ray-manager.(*Manager).GetTrafficAndReset(0xc000050680, 0x9d42e0, 0xc000451b50, 0x0, 0xc0007539d8)
	/go/pkg/mod/github.com/orvice/v2ray-manager@v0.0.0-20190226151834-0c371533e708/manager.go:112 +0x304
github.com/orvice/v2ray-mu/server.(*UserManager).saveUserTraffic(0xc000100540, 0xf74, 0x2b4e, 0xc0002ac4b6, 0x6, 0xc0002ac4d0, 0xb, 0x1, 0x1a2c9a1bf, 0x0, ...)
	/home/app/server/user.go:64 +0x9c
github.com/orvice/v2ray-mu/server.(*UserManager).saveTrafficDaemon(0xc000100540, 0x0, 0x0)
	/home/app/server/manager.go:78 +0x184
github.com/orvice/v2ray-mu/server.(*UserManager).saveTrafficDaemon-fm(0xbf1667e64d50089d, 0xdf942675d)
	/home/app/server/manager.go:65 +0x2a
github.com/orvice/kit/utils.(*Task).Run(0xc000100990)
	/go/pkg/mod/github.com/orvice/kit@v0.0.0-20190224124836-1d905413b870/utils/task.go:35 +0xb4
created by github.com/orvice/v2ray-mu/server.runJob
	/home/app/server/utils.go:14 +0xa0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x823de4]

goroutine 16 [running]:
github.com/orvice/v2ray-manager.(*Manager).GetTrafficAndReset(0xc000050700, 0x9d42e0, 0xc00054f150, 0x0, 0xc00066c9c8)
	/go/pkg/mod/github.com/orvice/v2ray-manager@v0.0.0-20190226151834-0c371533e708/manager.go:112 +0x304
github.com/orvice/v2ray-mu/server.(*UserManager).saveUserTraffic(0xc000100540, 0x191e, 0x3185, 0xc000224e46, 0x6, 0xc000224e80, 0xb, 0x1, 0x1680000000, 0x3126927, ...)
	/home/app/server/user.go:64 +0x9c
github.com/orvice/v2ray-mu/server.(*UserManager).saveTrafficDaemon(0xc000100540, 0x0, 0x0)
	/home/app/server/manager.go:78 +0x184
github.com/orvice/v2ray-mu/server.(*UserManager).saveTrafficDaemon-fm(0xbf1667f5dc190ab0, 0xdfa7aa32f)
	/home/app/server/manager.go:65 +0x2a
github.com/orvice/kit/utils.(*Task).Run(0xc000100870)
	/go/pkg/mod/github.com/orvice/kit@v0.0.0-20190224124836-1d905413b870/utils/task.go:35 +0xb4
created by github.com/orvice/v2ray-mu/server.runJob
	/home/app/server/utils.go:14 +0xa0
```

**Comment by orvice** [comment]
fixed, please update by pulling latest docker image.
